# Generated by Django 4.1.1 on 2022-12-14 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newIAPapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mission',
            name='freq',
        ),
        migrations.AlterField(
            model_name='mission',
            name='deadline',
            field=models.DateField(verbose_name='Крайний срок'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='descr',
            field=models.CharField(max_length=50, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='imp',
            field=models.CharField(choices=[('желательно', 'желательно'), ('важно', 'важно'), ('критически важно', 'критически важно'), ('жизненно важно', 'жизненно важно')], default='WE', max_length=20, verbose_name='Важность'),
        ),
        migrations.AlterField(
            model_name='mission',
            name='sphere',
            field=models.CharField(choices=[('учеба', 'учеба'), ('работа', 'работа'), ('здоровье', 'здоровье'), ('хобби', 'хобби'), ('иное', 'иное')], default='OT', max_length=20, verbose_name='Сфера'),
        ),
    ]
